// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6KmRu_LqD9r_BnA4jjWCmcka-3hFmc_w',
    appId: '1:781032335718:android:ab2338c8110ce991fbc0a7',
    messagingSenderId: '781032335718',
    projectId: 'gotrust-thaco-loyalty',
    storageBucket: 'gotrust-thaco-loyalty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByP_q4IvxDzAepARL_8yupjd7hxX5KdC8',
    appId: '1:781032335718:ios:15e7a72f55c94820fbc0a7',
    messagingSenderId: '781032335718',
    projectId: 'gotrust-thaco-loyalty',
    storageBucket: 'gotrust-thaco-loyalty.appspot.com',
    androidClientId: '781032335718-roe4ag160pq4as3gq71dkqmv8fmrofuj.apps.googleusercontent.com',
    iosClientId: '781032335718-5raje1bh2oi2fht6ilvfe9pr455sh8ir.apps.googleusercontent.com',
    iosBundleId: 'com.gotrust.thacoLoyalty2023',
  );
}
