name: source_base
description: This's a source create by GoTrust Team

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Custom package
  # gotrust_popup is package to show snackbar, popup fullscreen, base popup, popup do action
  # style of this package base on style of GoTrust Team
#  gotrust_popup:
#      git:
#        url: https://github.com/BobLee-GT/popup-package.git
  ##############

  #Fỉrebase Notification
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  #Firebase service
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  local_auth: ^2.2.0
  #Manage State
  get: ^4.6.6
  rxdart: ^0.27.7
  #Work with API
  dio: ^5.5.0+1
  http: ^1.2.1
  intl: ^0.19.0
  # Url luncher
  url_launcher: ^6.3.0
  #Font
  google_fonts: ^6.2.1
  #Loading animation
  flutter_easyloading: ^3.0.5
  #Image
  cached_network_image: ^3.3.1
  #Animation
  lottie: ^3.1.2
  # OTP pin field
  otp_pin_field: ^1.2.9
  #Save data to local
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  #Bottom bar
  awesome_bottom_bar: ^1.2.4
  #Load file svg
  flutter_svg: ^2.0.10+1
  #Deeplink
  app_links: ^6.1.4
  #Check connect wifi
  connectivity_plus: ^6.0.3
  #Copy text
  clipboard: ^0.1.3
  #other
  path_provider: ^2.1.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animation/
    - assets/images/
    - assets/popup/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
